#pragma once
#ifdef M5_TEST_NO_RADIOS
#define CONFIG_M5_CONNECTIVITY_WIFI_ENABLED 0
#define CONFIG_M5_CONNECTIVITY_BLE_ENABLED 0
#else
#define CONFIG_M5_CONNECTIVITY_WIFI_ENABLED 1
#define CONFIG_M5_CONNECTIVITY_BLE_ENABLED 1
#endif
